/**
 * Enrollment denominators, read from the committed `data/enrollment.json`.
 *
 * That file is generated by `scripts/fetch-enrollment.ts` from IPEDS and is
 * committed, so the build never touches the network. It currently ships **empty**:
 * the environment this was built in cannot reach nces.ed.gov, and the alternative
 * — hand-entering enrollment figures — is exactly the kind of unverifiable number
 * this project refuses to publish.
 *
 * The consequence is visible and intended: with no denominators, no club can be
 * ranked, and the standings page says so in as many words.
 */

import { readFileSync } from 'node:fs';
import { z } from 'zod';

const enrollmentFileSchema = z.object({
  source: z
    .object({
      title: z.string(),
      url: z.string().url(),
      accessed: z.string(),
    })
    .nullable(),
  generatedAt: z.string().nullable(),
  ipedsYear: z.number().int().nullable(),
  denominator: z.literal('undergraduate_enrollment'),
  /** Keyed by IPEDS UnitID as a string. */
  institutions: z.record(
    z.string(),
    z.object({
      name: z.string(),
      undergraduateEnrollment: z.number().int().nonnegative(),
    }),
  ),
});

export type EnrollmentFile = z.infer<typeof enrollmentFileSchema>;

let cached: EnrollmentFile | null = null;

export function loadEnrollment(): EnrollmentFile {
  if (cached) return cached;
  const path = new URL('../../../../data/enrollment.json', import.meta.url);
  const parsed = enrollmentFileSchema.parse(JSON.parse(readFileSync(path, 'utf8')));
  cached = parsed;
  return parsed;
}

/** Undergraduate enrollment for an IPEDS UnitID, or null when we do not have it. */
export function enrollmentFor(unitId: number | null | undefined): number | null {
  if (unitId === null || unitId === undefined) return null;
  const file = loadEnrollment();
  return file.institutions[String(unitId)]?.undergraduateEnrollment ?? null;
}

/** True when the fetch has never been run — drives the explanatory empty state. */
export function enrollmentIsEmpty(): boolean {
  return Object.keys(loadEnrollment().institutions).length === 0;
}
